name: Clean Deployments
on:
  workflow_dispatch:
jobs:
  delete_deployments:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
      contents: read
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Eliminar todos los despliegues
        uses: strumwolf/delete-deployment-environment@v3
        with:
          onlyRemoveDeployments: true
          token: ${{ secrets.GITHUB_TOKEN }}
