name: Clean Deployments

on:
  workflow_dispatch:

jobs:
  delete_deployments:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
      contents: read
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Delete All Deployments
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            const { data: deployments } = await github.rest.repos.listDeployments({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            
            console.log(`Se encontraron ${deployments.length} deployments.`);
            
            for (const deployment of deployments) {
              console.log(`Desactivando y borrando deployment ID: ${deployment.id} (${deployment.environment})`);
              
              await github.rest.repos.createDeploymentStatus({
                owner: context.repo.owner,
                repo: context.repo.repo,
                deployment_id: deployment.id,
                state: 'inactive'
              });
              
              await github.rest.repos.deleteDeployment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                deployment_id: deployment.id,
              });
            }
